// frontend.old/src/components/LeftSidebar.jsx
import "../assets/styles/LeftSidebar.css";

function Sidebar() {
  return (
    <>
      <section className="left-sidebar">
        <article id="menu-wrapper">
          <div className="search">
            <div className="search-button"></div>
            <div className="search-input"></div>
          </div>
          <div className="home">
            <div className="home-img"></div>
            <div className="home-title"></div>
          </div>
          <div className="playlists">
            <div className="playlists-img"></div>
            <div className="playlists-title"></div>
          </div>
        </article>
        <article id="playlist-title">
          <h1>Playlists</h1>
        </article>
        <article id="playlist-wrapper">
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
          <div className="playlist">
            <div className="playlist-img"></div>
            <div className="playlist-title"></div>
            <div className="playlist-author"></div>
          </div>
        </article>
      </section>
    </>
  );
}

export default Sidebar;

// frontend/src/components/LeftSidebarComponent.vue
<template>
  <section className="left-sidebar">
    <article id="menu-wrapper">
      <div className="search">
        <div className="search-button"></div>
        <div className="search-input"></div>
      </div>
      <div className="home">
        <div className="home-img"></div>
        <div className="home-title"></div>
      </div>
      <div className="playlists">
        <div className="playlists-img"></div>
        <div className="playlists-title"></div>
      </div>
    </article>
    <article id="playlist-title">
      <h1>Playlists</h1>
    </article>
    <article id="playlist-wrapper">
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
      <div className="playlist">
        <div className="playlist-img"></div>
        <div className="playlist-title"></div>
        <div className="playlist-author"></div>
      </div>
    </article>
  </section>
</template>

<script setup lang="ts">
import '../assets/styles/LeftSidebar.css'
</script>

<style scoped></style>
